baseurl      = "https://pereprogramming.com"
title        = "Pere Programming"
languageCode = "fr-fr"
theme        = "hello-friend-ng"
paginate     = 10
defaultContentLanguage = "fr"
enableEmoji  = true

[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04"

  # Subtitle for home
  homeSubtitle = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Parce que parler de code en français n'est pas sale."
  keywords = "dev, programmation, tutoriel, blog"
  images = ["logo.png"]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.fr]
    title = "Code, Amour et Rock'n'roll."
    subtitle = "Les histoires de pere programming"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Voir les autres posts"

    [languages.fr.params.logo]
      logoText = "pere programming"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "articles"
    name       = "Articles"
    url        = "/articles"
